-- Seed opzionale per `supabase db reset` (dopo le migrazioni).
-- Aggiungi qui gli utenti autorizzati, es.:
-- insert into public.members (email, full_name) values ('nome@dominio.it', 'Nome Cognome') on conflict (email) do nothing;
