-- Seed opzionale per `supabase db reset` (dopo le migrazioni).
-- Primo amministratore (sostituisci con la tua email Google):
-- insert into public.members (email, role)
-- values ('tuo.nome@dominio.it', 'admin')
-- on conflict (email) do nothing;
